/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * ChargingPeriod
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T06:10:29.834942772Z[GMT]")

public class ChargingPeriod {
  @SerializedName("start_date_time")
  private OffsetDateTime startDateTime = null;

  @SerializedName("dimensions")
  private List<CdrDimension> dimensions = null;

  @SerializedName("tariff_id")
  private String tariffId = null;

  public ChargingPeriod startDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Get startDateTime
   * @return startDateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }

  public ChargingPeriod dimensions(List<CdrDimension> dimensions) {
    this.dimensions = dimensions;
    return this;
  }

  public ChargingPeriod addDimensionsItem(CdrDimension dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<CdrDimension>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  @Schema(description = "")
  public List<CdrDimension> getDimensions() {
    return dimensions;
  }

  public void setDimensions(List<CdrDimension> dimensions) {
    this.dimensions = dimensions;
  }

  public ChargingPeriod tariffId(String tariffId) {
    this.tariffId = tariffId;
    return this;
  }

   /**
   * Get tariffId
   * @return tariffId
  **/
  @Schema(description = "")
  public String getTariffId() {
    return tariffId;
  }

  public void setTariffId(String tariffId) {
    this.tariffId = tariffId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargingPeriod chargingPeriod = (ChargingPeriod) o;
    return Objects.equals(this.startDateTime, chargingPeriod.startDateTime) &&
        Objects.equals(this.dimensions, chargingPeriod.dimensions) &&
        Objects.equals(this.tariffId, chargingPeriod.tariffId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDateTime, dimensions, tariffId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargingPeriod {\n");
    
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    tariffId: ").append(toIndentedString(tariffId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
