/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * ExceptionalPeriod
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T06:10:29.834942772Z[GMT]")

public class ExceptionalPeriod {
  @SerializedName("period_begin")
  private OffsetDateTime periodBegin = null;

  @SerializedName("period_end")
  private OffsetDateTime periodEnd = null;

  public ExceptionalPeriod periodBegin(OffsetDateTime periodBegin) {
    this.periodBegin = periodBegin;
    return this;
  }

   /**
   * Get periodBegin
   * @return periodBegin
  **/
  @Schema(description = "")
  public OffsetDateTime getPeriodBegin() {
    return periodBegin;
  }

  public void setPeriodBegin(OffsetDateTime periodBegin) {
    this.periodBegin = periodBegin;
  }

  public ExceptionalPeriod periodEnd(OffsetDateTime periodEnd) {
    this.periodEnd = periodEnd;
    return this;
  }

   /**
   * Get periodEnd
   * @return periodEnd
  **/
  @Schema(description = "")
  public OffsetDateTime getPeriodEnd() {
    return periodEnd;
  }

  public void setPeriodEnd(OffsetDateTime periodEnd) {
    this.periodEnd = periodEnd;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExceptionalPeriod exceptionalPeriod = (ExceptionalPeriod) o;
    return Objects.equals(this.periodBegin, exceptionalPeriod.periodBegin) &&
        Objects.equals(this.periodEnd, exceptionalPeriod.periodEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(periodBegin, periodEnd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExceptionalPeriod {\n");
    
    sb.append("    periodBegin: ").append(toIndentedString(periodBegin)).append("\n");
    sb.append("    periodEnd: ").append(toIndentedString(periodEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
