/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * StatusSchedule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T06:10:29.834942772Z[GMT]")

public class StatusSchedule {
  @SerializedName("period_begin")
  private OffsetDateTime periodBegin = null;

  @SerializedName("period_end")
  private OffsetDateTime periodEnd = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    @SerializedName("AVAILABLE")
    AVAILABLE("AVAILABLE"),
    @SerializedName("BLOCKED")
    BLOCKED("BLOCKED"),
    @SerializedName("CHARGING")
    CHARGING("CHARGING"),
    @SerializedName("INOPERATIVE")
    INOPERATIVE("INOPERATIVE"),
    @SerializedName("OUTOFORDER")
    OUTOFORDER("OUTOFORDER"),
    @SerializedName("PLANNED")
    PLANNED("PLANNED"),
    @SerializedName("REMOVED")
    REMOVED("REMOVED"),
    @SerializedName("RESERVED")
    RESERVED("RESERVED"),
    @SerializedName("UNKNOWN")
    UNKNOWN("UNKNOWN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  public StatusSchedule periodBegin(OffsetDateTime periodBegin) {
    this.periodBegin = periodBegin;
    return this;
  }

   /**
   * Get periodBegin
   * @return periodBegin
  **/
  @Schema(description = "")
  public OffsetDateTime getPeriodBegin() {
    return periodBegin;
  }

  public void setPeriodBegin(OffsetDateTime periodBegin) {
    this.periodBegin = periodBegin;
  }

  public StatusSchedule periodEnd(OffsetDateTime periodEnd) {
    this.periodEnd = periodEnd;
    return this;
  }

   /**
   * Get periodEnd
   * @return periodEnd
  **/
  @Schema(description = "")
  public OffsetDateTime getPeriodEnd() {
    return periodEnd;
  }

  public void setPeriodEnd(OffsetDateTime periodEnd) {
    this.periodEnd = periodEnd;
  }

  public StatusSchedule status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusSchedule statusSchedule = (StatusSchedule) o;
    return Objects.equals(this.periodBegin, statusSchedule.periodBegin) &&
        Objects.equals(this.periodEnd, statusSchedule.periodEnd) &&
        Objects.equals(this.status, statusSchedule.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(periodBegin, periodEnd, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusSchedule {\n");
    
    sb.append("    periodBegin: ").append(toIndentedString(periodBegin)).append("\n");
    sb.append("    periodEnd: ").append(toIndentedString(periodEnd)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
