/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * Tariff
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-01T06:10:29.834942772Z[GMT]")

public class Tariff {
  @SerializedName("country_code")
  private String countryCode = null;

  @SerializedName("party_id")
  private String partyId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("currency")
  private String currency = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    @SerializedName("AD_HOC_PAYMENT")
    AD_HOC_PAYMENT("AD_HOC_PAYMENT"),
    @SerializedName("PROFILE_CHEAP")
    PROFILE_CHEAP("PROFILE_CHEAP"),
    @SerializedName("PROFILE_FAST")
    PROFILE_FAST("PROFILE_FAST"),
    @SerializedName("REGULAR")
    REGULAR("REGULAR"),
    @SerializedName("PROFILE_GREEN")
    PROFILE_GREEN("PROFILE_GREEN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return TypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("tariff_alt_text")
  private List<DisplayText> tariffAltText = null;

  @SerializedName("tariff_alt_url")
  private String tariffAltUrl = null;

  @SerializedName("min_price")
  private Price minPrice = null;

  @SerializedName("max_price")
  private Price maxPrice = null;

  @SerializedName("elements")
  private List<TariffElement> elements = null;

  @SerializedName("start_date_time")
  private OffsetDateTime startDateTime = null;

  @SerializedName("end_date_time")
  private OffsetDateTime endDateTime = null;

  @SerializedName("energy_mix")
  private EnergyMix energyMix = null;

  @SerializedName("last_updated")
  private OffsetDateTime lastUpdated = null;

  public Tariff countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @Schema(description = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public Tariff partyId(String partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @Schema(description = "")
  public String getPartyId() {
    return partyId;
  }

  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }

  public Tariff id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Tariff currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(description = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Tariff type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Tariff tariffAltText(List<DisplayText> tariffAltText) {
    this.tariffAltText = tariffAltText;
    return this;
  }

  public Tariff addTariffAltTextItem(DisplayText tariffAltTextItem) {
    if (this.tariffAltText == null) {
      this.tariffAltText = new ArrayList<DisplayText>();
    }
    this.tariffAltText.add(tariffAltTextItem);
    return this;
  }

   /**
   * Get tariffAltText
   * @return tariffAltText
  **/
  @Schema(description = "")
  public List<DisplayText> getTariffAltText() {
    return tariffAltText;
  }

  public void setTariffAltText(List<DisplayText> tariffAltText) {
    this.tariffAltText = tariffAltText;
  }

  public Tariff tariffAltUrl(String tariffAltUrl) {
    this.tariffAltUrl = tariffAltUrl;
    return this;
  }

   /**
   * Get tariffAltUrl
   * @return tariffAltUrl
  **/
  @Schema(description = "")
  public String getTariffAltUrl() {
    return tariffAltUrl;
  }

  public void setTariffAltUrl(String tariffAltUrl) {
    this.tariffAltUrl = tariffAltUrl;
  }

  public Tariff minPrice(Price minPrice) {
    this.minPrice = minPrice;
    return this;
  }

   /**
   * Get minPrice
   * @return minPrice
  **/
  @Schema(description = "")
  public Price getMinPrice() {
    return minPrice;
  }

  public void setMinPrice(Price minPrice) {
    this.minPrice = minPrice;
  }

  public Tariff maxPrice(Price maxPrice) {
    this.maxPrice = maxPrice;
    return this;
  }

   /**
   * Get maxPrice
   * @return maxPrice
  **/
  @Schema(description = "")
  public Price getMaxPrice() {
    return maxPrice;
  }

  public void setMaxPrice(Price maxPrice) {
    this.maxPrice = maxPrice;
  }

  public Tariff elements(List<TariffElement> elements) {
    this.elements = elements;
    return this;
  }

  public Tariff addElementsItem(TariffElement elementsItem) {
    if (this.elements == null) {
      this.elements = new ArrayList<TariffElement>();
    }
    this.elements.add(elementsItem);
    return this;
  }

   /**
   * Get elements
   * @return elements
  **/
  @Schema(description = "")
  public List<TariffElement> getElements() {
    return elements;
  }

  public void setElements(List<TariffElement> elements) {
    this.elements = elements;
  }

  public Tariff startDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Get startDateTime
   * @return startDateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }

  public Tariff endDateTime(OffsetDateTime endDateTime) {
    this.endDateTime = endDateTime;
    return this;
  }

   /**
   * Get endDateTime
   * @return endDateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getEndDateTime() {
    return endDateTime;
  }

  public void setEndDateTime(OffsetDateTime endDateTime) {
    this.endDateTime = endDateTime;
  }

  public Tariff energyMix(EnergyMix energyMix) {
    this.energyMix = energyMix;
    return this;
  }

   /**
   * Get energyMix
   * @return energyMix
  **/
  @Schema(description = "")
  public EnergyMix getEnergyMix() {
    return energyMix;
  }

  public void setEnergyMix(EnergyMix energyMix) {
    this.energyMix = energyMix;
  }

  public Tariff lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tariff tariff = (Tariff) o;
    return Objects.equals(this.countryCode, tariff.countryCode) &&
        Objects.equals(this.partyId, tariff.partyId) &&
        Objects.equals(this.id, tariff.id) &&
        Objects.equals(this.currency, tariff.currency) &&
        Objects.equals(this.type, tariff.type) &&
        Objects.equals(this.tariffAltText, tariff.tariffAltText) &&
        Objects.equals(this.tariffAltUrl, tariff.tariffAltUrl) &&
        Objects.equals(this.minPrice, tariff.minPrice) &&
        Objects.equals(this.maxPrice, tariff.maxPrice) &&
        Objects.equals(this.elements, tariff.elements) &&
        Objects.equals(this.startDateTime, tariff.startDateTime) &&
        Objects.equals(this.endDateTime, tariff.endDateTime) &&
        Objects.equals(this.energyMix, tariff.energyMix) &&
        Objects.equals(this.lastUpdated, tariff.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, partyId, id, currency, type, tariffAltText, tariffAltUrl, minPrice, maxPrice, elements, startDateTime, endDateTime, energyMix, lastUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tariff {\n");
    
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tariffAltText: ").append(toIndentedString(tariffAltText)).append("\n");
    sb.append("    tariffAltUrl: ").append(toIndentedString(tariffAltUrl)).append("\n");
    sb.append("    minPrice: ").append(toIndentedString(minPrice)).append("\n");
    sb.append("    maxPrice: ").append(toIndentedString(maxPrice)).append("\n");
    sb.append("    elements: ").append(toIndentedString(elements)).append("\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
    sb.append("    energyMix: ").append(toIndentedString(energyMix)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
