/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.api;

import com.extrawest.ocpi221emsp_client.client.model.AbstractCommand;
import com.extrawest.ocpi221emsp_client.client.model.CommandResponseDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoCommandsControllerApi
 */
@Ignore
public class CpoCommandsControllerApiTest {

    private final CpoCommandsControllerApi api = new CpoCommandsControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCommandTest() {
        AbstractCommand body = null;
        String command = null;
        CommandResponseDTO response = api.postCommand(body, command);

        // TODO: test validations
    }
}
