/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.api;

import com.extrawest.ocpi221emsp_client.client.model.CdrDTO;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoCdrControllerApi
 */
@Ignore
public class CpoCdrControllerApiTest {

    private final CpoCdrControllerApi api = new CpoCdrControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCdr1Test() {
        OffsetDateTime dateFrom = null;
        OffsetDateTime dateTo = null;
        Integer offset = null;
        Integer limit = null;
        List<CdrDTO> response = api.getCdr1(dateFrom, dateTo, offset, limit);

        // TODO: test validations
    }
}
