/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.api;

import com.extrawest.ocpi221emsp_client.client.model.AbstractDomainObject;
import com.extrawest.ocpi221emsp_client.client.model.LocationDTO;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoLocationControllerApi
 */
@Ignore
public class CpoLocationControllerApiTest {

    private final CpoLocationControllerApi api = new CpoLocationControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocationEvseController1Test() {
        String locationId = null;
        String evseUid = null;
        String connectorId = null;
        AbstractDomainObject response = api.getLocationEvseController1(locationId, evseUid, connectorId);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLocationsTest() {
        OffsetDateTime dateFrom = null;
        OffsetDateTime dateTo = null;
        Integer offset = null;
        Integer limit = null;
        List<LocationDTO> response = api.getLocations(dateFrom, dateTo, offset, limit);

        // TODO: test validations
    }
}
