/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.api;

import com.extrawest.ocpi221emsp_client.client.model.ChargingPreferencesDTO;
import org.threeten.bp.OffsetDateTime;
import com.extrawest.ocpi221emsp_client.client.model.SessionDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CpoSessionsControllerApi
 */
@Ignore
public class CpoSessionsControllerApiTest {

    private final CpoSessionsControllerApi api = new CpoSessionsControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSessionsTest() {
        OffsetDateTime dateFrom = null;
        OffsetDateTime dateTo = null;
        Integer offset = null;
        Integer limit = null;
        List<SessionDTO> response = api.getSessions(dateFrom, dateTo, offset, limit);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putChargingPreferencesTest() {
        ChargingPreferencesDTO body = null;
        String sessionId = null;
        ChargingPreferencesDTO response = api.putChargingPreferences(body, sessionId);

        // TODO: test validations
    }
}
