/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.api;

import com.extrawest.ocpi221emsp_client.client.model.AuthorizationInfoResponseDTO;
import com.extrawest.ocpi221emsp_client.client.model.LocationReferencesRequestDTO;
import org.threeten.bp.OffsetDateTime;
import com.extrawest.ocpi221emsp_client.client.model.TokenDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmspTokenControllerApi
 */
@Ignore
public class EmspTokenControllerApiTest {

    private final EmspTokenControllerApi api = new EmspTokenControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTokenTest() {
        OffsetDateTime dateFrom = null;
        OffsetDateTime dateTo = null;
        Integer offset = null;
        Integer limit = null;
        List<TokenDTO> response = api.getToken(dateFrom, dateTo, offset, limit);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postTokenTest() {
        LocationReferencesRequestDTO body = null;
        String tokenUid = null;
        String type = null;
        AuthorizationInfoResponseDTO response = api.postToken(body, tokenUid, type);

        // TODO: test validations
    }
}
