/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.api;

import com.extrawest.ocpi221emsp_client.ApiCallback;
import com.extrawest.ocpi221emsp_client.ApiClient;
import com.extrawest.ocpi221emsp_client.ApiException;
import com.extrawest.ocpi221emsp_client.ApiResponse;
import com.extrawest.ocpi221emsp_client.Configuration;
import com.extrawest.ocpi221emsp_client.Pair;
import com.extrawest.ocpi221emsp_client.ProgressRequestBody;
import com.extrawest.ocpi221emsp_client.ProgressResponseBody;

import com.extrawest.ocpi221emsp_client.model.TariffDTO;
import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EmspTariffControllerApi {
    private ApiClient apiClient;

    public EmspTariffControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public EmspTariffControllerApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for deleteTariff
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteTariffCall(String countryCode, String partyId, String tariffId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/emsp/api/2.2.1/tariffs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (countryCode != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("country_code", countryCode));
        if (partyId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("party_id", partyId));
        if (tariffId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("tariff_id", tariffId));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteTariffValidateBeforeCall(String countryCode, String partyId, String tariffId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'countryCode' is set
        if (countryCode == null) {
            throw new ApiException("Missing the required parameter 'countryCode' when calling deleteTariff(Async)");
        }
        // verify the required parameter 'partyId' is set
        if (partyId == null) {
            throw new ApiException("Missing the required parameter 'partyId' when calling deleteTariff(Async)");
        }
        // verify the required parameter 'tariffId' is set
        if (tariffId == null) {
            throw new ApiException("Missing the required parameter 'tariffId' when calling deleteTariff(Async)");
        }
        
        com.squareup.okhttp.Call call = deleteTariffCall(countryCode, partyId, tariffId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * 
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void deleteTariff(String countryCode, String partyId, String tariffId) throws ApiException {
        deleteTariffWithHttpInfo(countryCode, partyId, tariffId);
    }

    /**
     * 
     * 
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> deleteTariffWithHttpInfo(String countryCode, String partyId, String tariffId) throws ApiException {
        com.squareup.okhttp.Call call = deleteTariffValidateBeforeCall(countryCode, partyId, tariffId, null, null);
        return apiClient.execute(call);
    }

    /**
     *  (asynchronously)
     * 
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteTariffAsync(String countryCode, String partyId, String tariffId, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteTariffValidateBeforeCall(countryCode, partyId, tariffId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for getTariff
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getTariffCall(String countryCode, String partyId, String tariffId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/emsp/api/2.2.1/tariffs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (countryCode != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("country_code", countryCode));
        if (partyId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("party_id", partyId));
        if (tariffId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("tariff_id", tariffId));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getTariffValidateBeforeCall(String countryCode, String partyId, String tariffId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'countryCode' is set
        if (countryCode == null) {
            throw new ApiException("Missing the required parameter 'countryCode' when calling getTariff(Async)");
        }
        // verify the required parameter 'partyId' is set
        if (partyId == null) {
            throw new ApiException("Missing the required parameter 'partyId' when calling getTariff(Async)");
        }
        // verify the required parameter 'tariffId' is set
        if (tariffId == null) {
            throw new ApiException("Missing the required parameter 'tariffId' when calling getTariff(Async)");
        }
        
        com.squareup.okhttp.Call call = getTariffCall(countryCode, partyId, tariffId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * 
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @return TariffDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public TariffDTO getTariff(String countryCode, String partyId, String tariffId) throws ApiException {
        ApiResponse<TariffDTO> resp = getTariffWithHttpInfo(countryCode, partyId, tariffId);
        return resp.getData();
    }

    /**
     * 
     * 
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @return ApiResponse&lt;TariffDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<TariffDTO> getTariffWithHttpInfo(String countryCode, String partyId, String tariffId) throws ApiException {
        com.squareup.okhttp.Call call = getTariffValidateBeforeCall(countryCode, partyId, tariffId, null, null);
        Type localVarReturnType = new TypeToken<TariffDTO>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getTariffAsync(String countryCode, String partyId, String tariffId, final ApiCallback<TariffDTO> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getTariffValidateBeforeCall(countryCode, partyId, tariffId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<TariffDTO>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for saveTariff
     * @param body  (required)
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call saveTariffCall(TariffDTO body, String countryCode, String partyId, String tariffId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/emsp/api/2.2.1/tariffs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (countryCode != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("country_code", countryCode));
        if (partyId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("party_id", partyId));
        if (tariffId != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("tariff_id", tariffId));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call saveTariffValidateBeforeCall(TariffDTO body, String countryCode, String partyId, String tariffId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling saveTariff(Async)");
        }
        // verify the required parameter 'countryCode' is set
        if (countryCode == null) {
            throw new ApiException("Missing the required parameter 'countryCode' when calling saveTariff(Async)");
        }
        // verify the required parameter 'partyId' is set
        if (partyId == null) {
            throw new ApiException("Missing the required parameter 'partyId' when calling saveTariff(Async)");
        }
        // verify the required parameter 'tariffId' is set
        if (tariffId == null) {
            throw new ApiException("Missing the required parameter 'tariffId' when calling saveTariff(Async)");
        }
        
        com.squareup.okhttp.Call call = saveTariffCall(body, countryCode, partyId, tariffId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * 
     * @param body  (required)
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void saveTariff(TariffDTO body, String countryCode, String partyId, String tariffId) throws ApiException {
        saveTariffWithHttpInfo(body, countryCode, partyId, tariffId);
    }

    /**
     * 
     * 
     * @param body  (required)
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> saveTariffWithHttpInfo(TariffDTO body, String countryCode, String partyId, String tariffId) throws ApiException {
        com.squareup.okhttp.Call call = saveTariffValidateBeforeCall(body, countryCode, partyId, tariffId, null, null);
        return apiClient.execute(call);
    }

    /**
     *  (asynchronously)
     * 
     * @param body  (required)
     * @param countryCode  (required)
     * @param partyId  (required)
     * @param tariffId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call saveTariffAsync(TariffDTO body, String countryCode, String partyId, String tariffId, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = saveTariffValidateBeforeCall(body, countryCode, partyId, tariffId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
