/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ChargingProfilePeriod
 */



public class ChargingProfilePeriod {
  @JsonProperty("start_period")
  private Integer startPeriod = null;

  @JsonProperty("limit")
  private Float limit = null;

  public ChargingProfilePeriod startPeriod(Integer startPeriod) {
    this.startPeriod = startPeriod;
    return this;
  }

   /**
   * Get startPeriod
   * @return startPeriod
  **/
  @Schema(description = "")
  public Integer getStartPeriod() {
    return startPeriod;
  }

  public void setStartPeriod(Integer startPeriod) {
    this.startPeriod = startPeriod;
  }

  public ChargingProfilePeriod limit(Float limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @Schema(description = "")
  public Float getLimit() {
    return limit;
  }

  public void setLimit(Float limit) {
    this.limit = limit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargingProfilePeriod chargingProfilePeriod = (ChargingProfilePeriod) o;
    return Objects.equals(this.startPeriod, chargingProfilePeriod.startPeriod) &&
        Objects.equals(this.limit, chargingProfilePeriod.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startPeriod, limit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargingProfilePeriod {\n");
    
    sb.append("    startPeriod: ").append(toIndentedString(startPeriod)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
