/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.extrawest.ocpi221emsp_client.client.model.DisplayText;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * CommandResponseDTO
 */



public class CommandResponseDTO {
  /**
   * Gets or Sets result
   */
  public enum ResultEnum {
    NOT_SUPPORTED("NOT_SUPPORTED"),
    REJECTED("REJECTED"),
    ACCEPTED("ACCEPTED"),
    UNKNOWN_SESSION("UNKNOWN_SESSION");

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ResultEnum fromValue(String input) {
      for (ResultEnum b : ResultEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("result")
  private ResultEnum result = null;

  @JsonProperty("timeout")
  private Integer timeout = null;

  @JsonProperty("message")
  private List<DisplayText> message = null;

  public CommandResponseDTO result(ResultEnum result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @Schema(required = true, description = "")
  public ResultEnum getResult() {
    return result;
  }

  public void setResult(ResultEnum result) {
    this.result = result;
  }

  public CommandResponseDTO timeout(Integer timeout) {
    this.timeout = timeout;
    return this;
  }

   /**
   * Get timeout
   * @return timeout
  **/
  @Schema(required = true, description = "")
  public Integer getTimeout() {
    return timeout;
  }

  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }

  public CommandResponseDTO message(List<DisplayText> message) {
    this.message = message;
    return this;
  }

  public CommandResponseDTO addMessageItem(DisplayText messageItem) {
    if (this.message == null) {
      this.message = new ArrayList<DisplayText>();
    }
    this.message.add(messageItem);
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public List<DisplayText> getMessage() {
    return message;
  }

  public void setMessage(List<DisplayText> message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandResponseDTO commandResponseDTO = (CommandResponseDTO) o;
    return Objects.equals(this.result, commandResponseDTO.result) &&
        Objects.equals(this.timeout, commandResponseDTO.timeout) &&
        Objects.equals(this.message, commandResponseDTO.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, timeout, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandResponseDTO {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
