/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * Connector
 */



public class Connector {
  @JsonProperty("url")
  private String url = null;

  @JsonProperty("id")
  private String id = null;

  /**
   * Gets or Sets standard
   */
  public enum StandardEnum {
    CHADEMO("CHADEMO"),
    CHAOJI("CHAOJI"),
    DOMESTIC_A("DOMESTIC_A"),
    DOMESTIC_B("DOMESTIC_B"),
    DOMESTIC_C("DOMESTIC_C"),
    DOMESTIC_D("DOMESTIC_D"),
    DOMESTIC_E("DOMESTIC_E"),
    DOMESTIC_F("DOMESTIC_F"),
    DOMESTIC_G("DOMESTIC_G"),
    DOMESTIC_H("DOMESTIC_H"),
    DOMESTIC_I("DOMESTIC_I"),
    DOMESTIC_J("DOMESTIC_J"),
    DOMESTIC_K("DOMESTIC_K"),
    DOMESTIC_L("DOMESTIC_L"),
    DOMESTIC_M("DOMESTIC_M"),
    DOMESTIC_N("DOMESTIC_N"),
    DOMESTIC_O("DOMESTIC_O"),
    GBT_AC("GBT_AC"),
    GBT_DC("GBT_DC"),
    IEC_60309_2_SINGLE_16("IEC_60309_2_single_16"),
    IEC_60309_2_THREE_16("IEC_60309_2_three_16"),
    IEC_60309_2_THREE_32("IEC_60309_2_three_32"),
    IEC_60309_2_THREE_64("IEC_60309_2_three_64"),
    IEC_62196_T1("IEC_62196_T1"),
    IEC_62196_T1_COMBO("IEC_62196_T1_COMBO"),
    IEC_62196_T2("IEC_62196_T2"),
    IEC_62196_T2_COMBO("IEC_62196_T2_COMBO"),
    IEC_62196_T3A("IEC_62196_T3A"),
    IEC_62196_T3C("IEC_62196_T3C"),
    NEMA_5_20("NEMA_5_20"),
    NEMA_6_30("NEMA_6_30"),
    NEMA_6_50("NEMA_6_50"),
    NEMA_10_30("NEMA_10_30"),
    NEMA_10_50("NEMA_10_50"),
    NEMA_14_30("NEMA_14_30"),
    NEMA_14_50("NEMA_14_50"),
    PANTOGRAPH_BOTTOM_UP("PANTOGRAPH_BOTTOM_UP"),
    PANTOGRAPH_TOP_DOWN("PANTOGRAPH_TOP_DOWN"),
    TESLA_R("TESLA_R"),
    TESLA_S("TESLA_S");

    private String value;

    StandardEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StandardEnum fromValue(String input) {
      for (StandardEnum b : StandardEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("standard")
  private StandardEnum standard = null;

  /**
   * Gets or Sets format
   */
  public enum FormatEnum {
    SOCKET("SOCKET"),
    CABLE("CABLE");

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FormatEnum fromValue(String input) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("format")
  private FormatEnum format = null;

  /**
   * Gets or Sets powerType
   */
  public enum PowerTypeEnum {
    AC_1_PHASE("AC_1_PHASE"),
    AC_2_PHASE("AC_2_PHASE"),
    AC_2_PHASE_SPLIT("AC_2_PHASE_SPLIT"),
    AC_3_PHASE("AC_3_PHASE"),
    DC("DC");

    private String value;

    PowerTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PowerTypeEnum fromValue(String input) {
      for (PowerTypeEnum b : PowerTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("power_type")
  private PowerTypeEnum powerType = null;

  @JsonProperty("max_voltage")
  private Integer maxVoltage = null;

  @JsonProperty("max_amperage")
  private Integer maxAmperage = null;

  @JsonProperty("max_electric_power")
  private Integer maxElectricPower = null;

  @JsonProperty("tariff_ids")
  private List<String> tariffIds = null;

  @JsonProperty("terms_and_conditions")
  private String termsAndConditions = null;

  @JsonProperty("last_updated")
  private OffsetDateTime lastUpdated = null;

  public Connector url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Connector id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Connector standard(StandardEnum standard) {
    this.standard = standard;
    return this;
  }

   /**
   * Get standard
   * @return standard
  **/
  @Schema(description = "")
  public StandardEnum getStandard() {
    return standard;
  }

  public void setStandard(StandardEnum standard) {
    this.standard = standard;
  }

  public Connector format(FormatEnum format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @Schema(description = "")
  public FormatEnum getFormat() {
    return format;
  }

  public void setFormat(FormatEnum format) {
    this.format = format;
  }

  public Connector powerType(PowerTypeEnum powerType) {
    this.powerType = powerType;
    return this;
  }

   /**
   * Get powerType
   * @return powerType
  **/
  @Schema(description = "")
  public PowerTypeEnum getPowerType() {
    return powerType;
  }

  public void setPowerType(PowerTypeEnum powerType) {
    this.powerType = powerType;
  }

  public Connector maxVoltage(Integer maxVoltage) {
    this.maxVoltage = maxVoltage;
    return this;
  }

   /**
   * Get maxVoltage
   * @return maxVoltage
  **/
  @Schema(description = "")
  public Integer getMaxVoltage() {
    return maxVoltage;
  }

  public void setMaxVoltage(Integer maxVoltage) {
    this.maxVoltage = maxVoltage;
  }

  public Connector maxAmperage(Integer maxAmperage) {
    this.maxAmperage = maxAmperage;
    return this;
  }

   /**
   * Get maxAmperage
   * @return maxAmperage
  **/
  @Schema(description = "")
  public Integer getMaxAmperage() {
    return maxAmperage;
  }

  public void setMaxAmperage(Integer maxAmperage) {
    this.maxAmperage = maxAmperage;
  }

  public Connector maxElectricPower(Integer maxElectricPower) {
    this.maxElectricPower = maxElectricPower;
    return this;
  }

   /**
   * Get maxElectricPower
   * @return maxElectricPower
  **/
  @Schema(description = "")
  public Integer getMaxElectricPower() {
    return maxElectricPower;
  }

  public void setMaxElectricPower(Integer maxElectricPower) {
    this.maxElectricPower = maxElectricPower;
  }

  public Connector tariffIds(List<String> tariffIds) {
    this.tariffIds = tariffIds;
    return this;
  }

  public Connector addTariffIdsItem(String tariffIdsItem) {
    if (this.tariffIds == null) {
      this.tariffIds = new ArrayList<String>();
    }
    this.tariffIds.add(tariffIdsItem);
    return this;
  }

   /**
   * Get tariffIds
   * @return tariffIds
  **/
  @Schema(description = "")
  public List<String> getTariffIds() {
    return tariffIds;
  }

  public void setTariffIds(List<String> tariffIds) {
    this.tariffIds = tariffIds;
  }

  public Connector termsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
    return this;
  }

   /**
   * Get termsAndConditions
   * @return termsAndConditions
  **/
  @Schema(description = "")
  public String getTermsAndConditions() {
    return termsAndConditions;
  }

  public void setTermsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
  }

  public Connector lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Connector connector = (Connector) o;
    return Objects.equals(this.url, connector.url) &&
        Objects.equals(this.id, connector.id) &&
        Objects.equals(this.standard, connector.standard) &&
        Objects.equals(this.format, connector.format) &&
        Objects.equals(this.powerType, connector.powerType) &&
        Objects.equals(this.maxVoltage, connector.maxVoltage) &&
        Objects.equals(this.maxAmperage, connector.maxAmperage) &&
        Objects.equals(this.maxElectricPower, connector.maxElectricPower) &&
        Objects.equals(this.tariffIds, connector.tariffIds) &&
        Objects.equals(this.termsAndConditions, connector.termsAndConditions) &&
        Objects.equals(this.lastUpdated, connector.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, id, standard, format, powerType, maxVoltage, maxAmperage, maxElectricPower, tariffIds, termsAndConditions, lastUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Connector {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    powerType: ").append(toIndentedString(powerType)).append("\n");
    sb.append("    maxVoltage: ").append(toIndentedString(maxVoltage)).append("\n");
    sb.append("    maxAmperage: ").append(toIndentedString(maxAmperage)).append("\n");
    sb.append("    maxElectricPower: ").append(toIndentedString(maxElectricPower)).append("\n");
    sb.append("    tariffIds: ").append(toIndentedString(tariffIds)).append("\n");
    sb.append("    termsAndConditions: ").append(toIndentedString(termsAndConditions)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
