/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.extrawest.ocpi221emsp_client.client.model.Connector;
import com.extrawest.ocpi221emsp_client.client.model.DisplayText;
import com.extrawest.ocpi221emsp_client.client.model.GeoLocation;
import com.extrawest.ocpi221emsp_client.client.model.Image;
import com.extrawest.ocpi221emsp_client.client.model.StatusSchedule;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * EVSE
 */



public class EVSE {
  @JsonProperty("uid")
  private String uid = null;

  @JsonProperty("evse_id")
  private String evseId = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    AVAILABLE("AVAILABLE"),
    BLOCKED("BLOCKED"),
    CHARGING("CHARGING"),
    INOPERATIVE("INOPERATIVE"),
    OUTOFORDER("OUTOFORDER"),
    PLANNED("PLANNED"),
    REMOVED("REMOVED"),
    RESERVED("RESERVED"),
    UNKNOWN("UNKNOWN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("status_schedule")
  private List<StatusSchedule> statusSchedule = null;

  /**
   * Gets or Sets capabilities
   */
  public enum CapabilitiesEnum {
    CHARGING_PROFILE_CAPABLE("CHARGING_PROFILE_CAPABLE"),
    CHARGING_PREFERENCES_CAPABLE("CHARGING_PREFERENCES_CAPABLE"),
    CHIP_CARD_SUPPORT("CHIP_CARD_SUPPORT"),
    CONTACTLESS_CARD_SUPPORT("CONTACTLESS_CARD_SUPPORT"),
    CREDIT_CARD_PAYABLE("CREDIT_CARD_PAYABLE"),
    DEBIT_CARD_PAYABLE("DEBIT_CARD_PAYABLE"),
    PED_TERMINAL("PED_TERMINAL"),
    REMOTE_START_STOP_CAPABLE("REMOTE_START_STOP_CAPABLE"),
    RESERVABLE("RESERVABLE"),
    RFID_READER("RFID_READER"),
    START_SESSION_CONNECTOR_REQUIRED("START_SESSION_CONNECTOR_REQUIRED"),
    TOKEN_GROUP_CAPABLE("TOKEN_GROUP_CAPABLE"),
    UNLOCK_CAPABLE("UNLOCK_CAPABLE");

    private String value;

    CapabilitiesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CapabilitiesEnum fromValue(String input) {
      for (CapabilitiesEnum b : CapabilitiesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("capabilities")
  private List<CapabilitiesEnum> capabilities = null;

  @JsonProperty("connectors")
  private List<Connector> connectors = null;

  @JsonProperty("floor_level")
  private String floorLevel = null;

  @JsonProperty("coordinates")
  private GeoLocation coordinates = null;

  @JsonProperty("physical_reference")
  private String physicalReference = null;

  @JsonProperty("directions")
  private List<DisplayText> directions = null;

  /**
   * Gets or Sets parkingRestrictions
   */
  public enum ParkingRestrictionsEnum {
    EV_ONLY("EV_ONLY"),
    PLUGGED("PLUGGED"),
    DISABLED("DISABLED"),
    CUSTOMERS("CUSTOMERS"),
    MOTORCYCLES("MOTORCYCLES");

    private String value;

    ParkingRestrictionsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ParkingRestrictionsEnum fromValue(String input) {
      for (ParkingRestrictionsEnum b : ParkingRestrictionsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("parking_restrictions")
  private List<ParkingRestrictionsEnum> parkingRestrictions = null;

  @JsonProperty("images")
  private List<Image> images = null;

  @JsonProperty("last_updated")
  private OffsetDateTime lastUpdated = null;

  public EVSE uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @Schema(description = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public EVSE evseId(String evseId) {
    this.evseId = evseId;
    return this;
  }

   /**
   * Get evseId
   * @return evseId
  **/
  @Schema(description = "")
  public String getEvseId() {
    return evseId;
  }

  public void setEvseId(String evseId) {
    this.evseId = evseId;
  }

  public EVSE status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public EVSE statusSchedule(List<StatusSchedule> statusSchedule) {
    this.statusSchedule = statusSchedule;
    return this;
  }

  public EVSE addStatusScheduleItem(StatusSchedule statusScheduleItem) {
    if (this.statusSchedule == null) {
      this.statusSchedule = new ArrayList<StatusSchedule>();
    }
    this.statusSchedule.add(statusScheduleItem);
    return this;
  }

   /**
   * Get statusSchedule
   * @return statusSchedule
  **/
  @Schema(description = "")
  public List<StatusSchedule> getStatusSchedule() {
    return statusSchedule;
  }

  public void setStatusSchedule(List<StatusSchedule> statusSchedule) {
    this.statusSchedule = statusSchedule;
  }

  public EVSE capabilities(List<CapabilitiesEnum> capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  public EVSE addCapabilitiesItem(CapabilitiesEnum capabilitiesItem) {
    if (this.capabilities == null) {
      this.capabilities = new ArrayList<CapabilitiesEnum>();
    }
    this.capabilities.add(capabilitiesItem);
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @Schema(description = "")
  public List<CapabilitiesEnum> getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(List<CapabilitiesEnum> capabilities) {
    this.capabilities = capabilities;
  }

  public EVSE connectors(List<Connector> connectors) {
    this.connectors = connectors;
    return this;
  }

  public EVSE addConnectorsItem(Connector connectorsItem) {
    if (this.connectors == null) {
      this.connectors = new ArrayList<Connector>();
    }
    this.connectors.add(connectorsItem);
    return this;
  }

   /**
   * Get connectors
   * @return connectors
  **/
  @Schema(description = "")
  public List<Connector> getConnectors() {
    return connectors;
  }

  public void setConnectors(List<Connector> connectors) {
    this.connectors = connectors;
  }

  public EVSE floorLevel(String floorLevel) {
    this.floorLevel = floorLevel;
    return this;
  }

   /**
   * Get floorLevel
   * @return floorLevel
  **/
  @Schema(description = "")
  public String getFloorLevel() {
    return floorLevel;
  }

  public void setFloorLevel(String floorLevel) {
    this.floorLevel = floorLevel;
  }

  public EVSE coordinates(GeoLocation coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @Schema(description = "")
  public GeoLocation getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(GeoLocation coordinates) {
    this.coordinates = coordinates;
  }

  public EVSE physicalReference(String physicalReference) {
    this.physicalReference = physicalReference;
    return this;
  }

   /**
   * Get physicalReference
   * @return physicalReference
  **/
  @Schema(description = "")
  public String getPhysicalReference() {
    return physicalReference;
  }

  public void setPhysicalReference(String physicalReference) {
    this.physicalReference = physicalReference;
  }

  public EVSE directions(List<DisplayText> directions) {
    this.directions = directions;
    return this;
  }

  public EVSE addDirectionsItem(DisplayText directionsItem) {
    if (this.directions == null) {
      this.directions = new ArrayList<DisplayText>();
    }
    this.directions.add(directionsItem);
    return this;
  }

   /**
   * Get directions
   * @return directions
  **/
  @Schema(description = "")
  public List<DisplayText> getDirections() {
    return directions;
  }

  public void setDirections(List<DisplayText> directions) {
    this.directions = directions;
  }

  public EVSE parkingRestrictions(List<ParkingRestrictionsEnum> parkingRestrictions) {
    this.parkingRestrictions = parkingRestrictions;
    return this;
  }

  public EVSE addParkingRestrictionsItem(ParkingRestrictionsEnum parkingRestrictionsItem) {
    if (this.parkingRestrictions == null) {
      this.parkingRestrictions = new ArrayList<ParkingRestrictionsEnum>();
    }
    this.parkingRestrictions.add(parkingRestrictionsItem);
    return this;
  }

   /**
   * Get parkingRestrictions
   * @return parkingRestrictions
  **/
  @Schema(description = "")
  public List<ParkingRestrictionsEnum> getParkingRestrictions() {
    return parkingRestrictions;
  }

  public void setParkingRestrictions(List<ParkingRestrictionsEnum> parkingRestrictions) {
    this.parkingRestrictions = parkingRestrictions;
  }

  public EVSE images(List<Image> images) {
    this.images = images;
    return this;
  }

  public EVSE addImagesItem(Image imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<Image>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @Schema(description = "")
  public List<Image> getImages() {
    return images;
  }

  public void setImages(List<Image> images) {
    this.images = images;
  }

  public EVSE lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @Schema(description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EVSE EVSE = (EVSE) o;
    return Objects.equals(this.uid, EVSE.uid) &&
        Objects.equals(this.evseId, EVSE.evseId) &&
        Objects.equals(this.status, EVSE.status) &&
        Objects.equals(this.statusSchedule, EVSE.statusSchedule) &&
        Objects.equals(this.capabilities, EVSE.capabilities) &&
        Objects.equals(this.connectors, EVSE.connectors) &&
        Objects.equals(this.floorLevel, EVSE.floorLevel) &&
        Objects.equals(this.coordinates, EVSE.coordinates) &&
        Objects.equals(this.physicalReference, EVSE.physicalReference) &&
        Objects.equals(this.directions, EVSE.directions) &&
        Objects.equals(this.parkingRestrictions, EVSE.parkingRestrictions) &&
        Objects.equals(this.images, EVSE.images) &&
        Objects.equals(this.lastUpdated, EVSE.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, evseId, status, statusSchedule, capabilities, connectors, floorLevel, coordinates, physicalReference, directions, parkingRestrictions, images, lastUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EVSE {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    evseId: ").append(toIndentedString(evseId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusSchedule: ").append(toIndentedString(statusSchedule)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    connectors: ").append(toIndentedString(connectors)).append("\n");
    sb.append("    floorLevel: ").append(toIndentedString(floorLevel)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    physicalReference: ").append(toIndentedString(physicalReference)).append("\n");
    sb.append("    directions: ").append(toIndentedString(directions)).append("\n");
    sb.append("    parkingRestrictions: ").append(toIndentedString(parkingRestrictions)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
