/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.extrawest.ocpi221emsp_client.client.model.ExceptionalPeriod;
import com.extrawest.ocpi221emsp_client.client.model.RegularHours;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Hours
 */



public class Hours {
  @JsonProperty("twentyfourseven")
  private Boolean twentyfourseven = null;

  @JsonProperty("regular_hours")
  private List<RegularHours> regularHours = null;

  @JsonProperty("exceptional_openings")
  private List<ExceptionalPeriod> exceptionalOpenings = null;

  @JsonProperty("exceptional_closings")
  private List<ExceptionalPeriod> exceptionalClosings = null;

  public Hours twentyfourseven(Boolean twentyfourseven) {
    this.twentyfourseven = twentyfourseven;
    return this;
  }

   /**
   * Get twentyfourseven
   * @return twentyfourseven
  **/
  @Schema(description = "")
  public Boolean isTwentyfourseven() {
    return twentyfourseven;
  }

  public void setTwentyfourseven(Boolean twentyfourseven) {
    this.twentyfourseven = twentyfourseven;
  }

  public Hours regularHours(List<RegularHours> regularHours) {
    this.regularHours = regularHours;
    return this;
  }

  public Hours addRegularHoursItem(RegularHours regularHoursItem) {
    if (this.regularHours == null) {
      this.regularHours = new ArrayList<RegularHours>();
    }
    this.regularHours.add(regularHoursItem);
    return this;
  }

   /**
   * Get regularHours
   * @return regularHours
  **/
  @Schema(description = "")
  public List<RegularHours> getRegularHours() {
    return regularHours;
  }

  public void setRegularHours(List<RegularHours> regularHours) {
    this.regularHours = regularHours;
  }

  public Hours exceptionalOpenings(List<ExceptionalPeriod> exceptionalOpenings) {
    this.exceptionalOpenings = exceptionalOpenings;
    return this;
  }

  public Hours addExceptionalOpeningsItem(ExceptionalPeriod exceptionalOpeningsItem) {
    if (this.exceptionalOpenings == null) {
      this.exceptionalOpenings = new ArrayList<ExceptionalPeriod>();
    }
    this.exceptionalOpenings.add(exceptionalOpeningsItem);
    return this;
  }

   /**
   * Get exceptionalOpenings
   * @return exceptionalOpenings
  **/
  @Schema(description = "")
  public List<ExceptionalPeriod> getExceptionalOpenings() {
    return exceptionalOpenings;
  }

  public void setExceptionalOpenings(List<ExceptionalPeriod> exceptionalOpenings) {
    this.exceptionalOpenings = exceptionalOpenings;
  }

  public Hours exceptionalClosings(List<ExceptionalPeriod> exceptionalClosings) {
    this.exceptionalClosings = exceptionalClosings;
    return this;
  }

  public Hours addExceptionalClosingsItem(ExceptionalPeriod exceptionalClosingsItem) {
    if (this.exceptionalClosings == null) {
      this.exceptionalClosings = new ArrayList<ExceptionalPeriod>();
    }
    this.exceptionalClosings.add(exceptionalClosingsItem);
    return this;
  }

   /**
   * Get exceptionalClosings
   * @return exceptionalClosings
  **/
  @Schema(description = "")
  public List<ExceptionalPeriod> getExceptionalClosings() {
    return exceptionalClosings;
  }

  public void setExceptionalClosings(List<ExceptionalPeriod> exceptionalClosings) {
    this.exceptionalClosings = exceptionalClosings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hours hours = (Hours) o;
    return Objects.equals(this.twentyfourseven, hours.twentyfourseven) &&
        Objects.equals(this.regularHours, hours.regularHours) &&
        Objects.equals(this.exceptionalOpenings, hours.exceptionalOpenings) &&
        Objects.equals(this.exceptionalClosings, hours.exceptionalClosings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(twentyfourseven, regularHours, exceptionalOpenings, exceptionalClosings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hours {\n");
    
    sb.append("    twentyfourseven: ").append(toIndentedString(twentyfourseven)).append("\n");
    sb.append("    regularHours: ").append(toIndentedString(regularHours)).append("\n");
    sb.append("    exceptionalOpenings: ").append(toIndentedString(exceptionalOpenings)).append("\n");
    sb.append("    exceptionalClosings: ").append(toIndentedString(exceptionalClosings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
