/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.extrawest.ocpi221emsp_client.client.model.AdditionalGeoLocation;
import com.extrawest.ocpi221emsp_client.client.model.BusinessDetails;
import com.extrawest.ocpi221emsp_client.client.model.DisplayText;
import com.extrawest.ocpi221emsp_client.client.model.EVSE;
import com.extrawest.ocpi221emsp_client.client.model.EnergyMix;
import com.extrawest.ocpi221emsp_client.client.model.GeoLocation;
import com.extrawest.ocpi221emsp_client.client.model.Hours;
import com.extrawest.ocpi221emsp_client.client.model.Image;
import com.extrawest.ocpi221emsp_client.client.model.PublishTokenType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * LocationDTO
 */



public class LocationDTO {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("publish")
  private Boolean publish = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("address")
  private String address = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("coordinates")
  private GeoLocation coordinates = null;

  @JsonProperty("evses")
  private List<EVSE> evses = null;

  @JsonProperty("directions")
  private List<DisplayText> directions = null;

  @JsonProperty("operator")
  private BusinessDetails operator = null;

  @JsonProperty("subOperator")
  private BusinessDetails subOperator = null;

  @JsonProperty("owner")
  private BusinessDetails owner = null;

  /**
   * Gets or Sets facilities
   */
  public enum FacilitiesEnum {
    HOTEL("HOTEL"),
    RESTAURANT("RESTAURANT"),
    CAFE("CAFE"),
    MALL("MALL"),
    SUPERMARKET("SUPERMARKET"),
    SPORT("SPORT"),
    RECREATION_AREA("RECREATION_AREA"),
    NATURE("NATURE"),
    MUSEUM("MUSEUM"),
    BIKE_SHARING("BIKE_SHARING"),
    BUS_STOP("BUS_STOP"),
    TAXI_STAND("TAXI_STAND"),
    TRAM_STOP("TRAM_STOP"),
    METRO_STATION("METRO_STATION"),
    TRAIN_STATION("TRAIN_STATION"),
    AIRPORT("AIRPORT"),
    PARKING_LOT("PARKING_LOT"),
    CARPOOL_PARKING("CARPOOL_PARKING"),
    FUEL_STATION("FUEL_STATION"),
    WIFI("WIFI");

    private String value;

    FacilitiesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FacilitiesEnum fromValue(String input) {
      for (FacilitiesEnum b : FacilitiesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("facilities")
  private List<FacilitiesEnum> facilities = null;

  @JsonProperty("images")
  private List<Image> images = null;

  @JsonProperty("country_code")
  private String countryCode = null;

  @JsonProperty("party_id")
  private String partyId = null;

  @JsonProperty("publish_allowed_to")
  private List<PublishTokenType> publishAllowedTo = null;

  @JsonProperty("postal_code")
  private String postalCode = null;

  @JsonProperty("related_locations")
  private List<AdditionalGeoLocation> relatedLocations = null;

  /**
   * Gets or Sets parkingType
   */
  public enum ParkingTypeEnum {
    ALONG_MOTORWAY("ALONG_MOTORWAY"),
    PARKING_GARAGE("PARKING_GARAGE"),
    PARKING_LOT("PARKING_LOT"),
    ON_DRIVEWAY("ON_DRIVEWAY"),
    ON_STREET("ON_STREET"),
    UNDERGROUND_GARAGE("UNDERGROUND_GARAGE");

    private String value;

    ParkingTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ParkingTypeEnum fromValue(String input) {
      for (ParkingTypeEnum b : ParkingTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("parking_type")
  private ParkingTypeEnum parkingType = null;

  @JsonProperty("time_zone")
  private String timeZone = null;

  @JsonProperty("opening_times")
  private Hours openingTimes = null;

  @JsonProperty("charging_when_closed")
  private Boolean chargingWhenClosed = null;

  @JsonProperty("energy_mix")
  private EnergyMix energyMix = null;

  @JsonProperty("last_updated")
  private OffsetDateTime lastUpdated = null;

  public LocationDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LocationDTO publish(Boolean publish) {
    this.publish = publish;
    return this;
  }

   /**
   * Get publish
   * @return publish
  **/
  @Schema(required = true, description = "")
  public Boolean isPublish() {
    return publish;
  }

  public void setPublish(Boolean publish) {
    this.publish = publish;
  }

  public LocationDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LocationDTO address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public LocationDTO city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @Schema(description = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public LocationDTO state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @Schema(description = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public LocationDTO country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @Schema(description = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public LocationDTO coordinates(GeoLocation coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @Schema(required = true, description = "")
  public GeoLocation getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(GeoLocation coordinates) {
    this.coordinates = coordinates;
  }

  public LocationDTO evses(List<EVSE> evses) {
    this.evses = evses;
    return this;
  }

  public LocationDTO addEvsesItem(EVSE evsesItem) {
    if (this.evses == null) {
      this.evses = new ArrayList<EVSE>();
    }
    this.evses.add(evsesItem);
    return this;
  }

   /**
   * Get evses
   * @return evses
  **/
  @Schema(description = "")
  public List<EVSE> getEvses() {
    return evses;
  }

  public void setEvses(List<EVSE> evses) {
    this.evses = evses;
  }

  public LocationDTO directions(List<DisplayText> directions) {
    this.directions = directions;
    return this;
  }

  public LocationDTO addDirectionsItem(DisplayText directionsItem) {
    if (this.directions == null) {
      this.directions = new ArrayList<DisplayText>();
    }
    this.directions.add(directionsItem);
    return this;
  }

   /**
   * Get directions
   * @return directions
  **/
  @Schema(description = "")
  public List<DisplayText> getDirections() {
    return directions;
  }

  public void setDirections(List<DisplayText> directions) {
    this.directions = directions;
  }

  public LocationDTO operator(BusinessDetails operator) {
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @Schema(description = "")
  public BusinessDetails getOperator() {
    return operator;
  }

  public void setOperator(BusinessDetails operator) {
    this.operator = operator;
  }

  public LocationDTO subOperator(BusinessDetails subOperator) {
    this.subOperator = subOperator;
    return this;
  }

   /**
   * Get subOperator
   * @return subOperator
  **/
  @Schema(description = "")
  public BusinessDetails getSubOperator() {
    return subOperator;
  }

  public void setSubOperator(BusinessDetails subOperator) {
    this.subOperator = subOperator;
  }

  public LocationDTO owner(BusinessDetails owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @Schema(description = "")
  public BusinessDetails getOwner() {
    return owner;
  }

  public void setOwner(BusinessDetails owner) {
    this.owner = owner;
  }

  public LocationDTO facilities(List<FacilitiesEnum> facilities) {
    this.facilities = facilities;
    return this;
  }

  public LocationDTO addFacilitiesItem(FacilitiesEnum facilitiesItem) {
    if (this.facilities == null) {
      this.facilities = new ArrayList<FacilitiesEnum>();
    }
    this.facilities.add(facilitiesItem);
    return this;
  }

   /**
   * Get facilities
   * @return facilities
  **/
  @Schema(description = "")
  public List<FacilitiesEnum> getFacilities() {
    return facilities;
  }

  public void setFacilities(List<FacilitiesEnum> facilities) {
    this.facilities = facilities;
  }

  public LocationDTO images(List<Image> images) {
    this.images = images;
    return this;
  }

  public LocationDTO addImagesItem(Image imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<Image>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @Schema(description = "")
  public List<Image> getImages() {
    return images;
  }

  public void setImages(List<Image> images) {
    this.images = images;
  }

  public LocationDTO countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @Schema(required = true, description = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public LocationDTO partyId(String partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @Schema(required = true, description = "")
  public String getPartyId() {
    return partyId;
  }

  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }

  public LocationDTO publishAllowedTo(List<PublishTokenType> publishAllowedTo) {
    this.publishAllowedTo = publishAllowedTo;
    return this;
  }

  public LocationDTO addPublishAllowedToItem(PublishTokenType publishAllowedToItem) {
    if (this.publishAllowedTo == null) {
      this.publishAllowedTo = new ArrayList<PublishTokenType>();
    }
    this.publishAllowedTo.add(publishAllowedToItem);
    return this;
  }

   /**
   * Get publishAllowedTo
   * @return publishAllowedTo
  **/
  @Schema(description = "")
  public List<PublishTokenType> getPublishAllowedTo() {
    return publishAllowedTo;
  }

  public void setPublishAllowedTo(List<PublishTokenType> publishAllowedTo) {
    this.publishAllowedTo = publishAllowedTo;
  }

  public LocationDTO postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @Schema(description = "")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public LocationDTO relatedLocations(List<AdditionalGeoLocation> relatedLocations) {
    this.relatedLocations = relatedLocations;
    return this;
  }

  public LocationDTO addRelatedLocationsItem(AdditionalGeoLocation relatedLocationsItem) {
    if (this.relatedLocations == null) {
      this.relatedLocations = new ArrayList<AdditionalGeoLocation>();
    }
    this.relatedLocations.add(relatedLocationsItem);
    return this;
  }

   /**
   * Get relatedLocations
   * @return relatedLocations
  **/
  @Schema(description = "")
  public List<AdditionalGeoLocation> getRelatedLocations() {
    return relatedLocations;
  }

  public void setRelatedLocations(List<AdditionalGeoLocation> relatedLocations) {
    this.relatedLocations = relatedLocations;
  }

  public LocationDTO parkingType(ParkingTypeEnum parkingType) {
    this.parkingType = parkingType;
    return this;
  }

   /**
   * Get parkingType
   * @return parkingType
  **/
  @Schema(description = "")
  public ParkingTypeEnum getParkingType() {
    return parkingType;
  }

  public void setParkingType(ParkingTypeEnum parkingType) {
    this.parkingType = parkingType;
  }

  public LocationDTO timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @Schema(required = true, description = "")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public LocationDTO openingTimes(Hours openingTimes) {
    this.openingTimes = openingTimes;
    return this;
  }

   /**
   * Get openingTimes
   * @return openingTimes
  **/
  @Schema(description = "")
  public Hours getOpeningTimes() {
    return openingTimes;
  }

  public void setOpeningTimes(Hours openingTimes) {
    this.openingTimes = openingTimes;
  }

  public LocationDTO chargingWhenClosed(Boolean chargingWhenClosed) {
    this.chargingWhenClosed = chargingWhenClosed;
    return this;
  }

   /**
   * Get chargingWhenClosed
   * @return chargingWhenClosed
  **/
  @Schema(description = "")
  public Boolean isChargingWhenClosed() {
    return chargingWhenClosed;
  }

  public void setChargingWhenClosed(Boolean chargingWhenClosed) {
    this.chargingWhenClosed = chargingWhenClosed;
  }

  public LocationDTO energyMix(EnergyMix energyMix) {
    this.energyMix = energyMix;
    return this;
  }

   /**
   * Get energyMix
   * @return energyMix
  **/
  @Schema(description = "")
  public EnergyMix getEnergyMix() {
    return energyMix;
  }

  public void setEnergyMix(EnergyMix energyMix) {
    this.energyMix = energyMix;
  }

  public LocationDTO lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationDTO locationDTO = (LocationDTO) o;
    return Objects.equals(this.id, locationDTO.id) &&
        Objects.equals(this.publish, locationDTO.publish) &&
        Objects.equals(this.name, locationDTO.name) &&
        Objects.equals(this.address, locationDTO.address) &&
        Objects.equals(this.city, locationDTO.city) &&
        Objects.equals(this.state, locationDTO.state) &&
        Objects.equals(this.country, locationDTO.country) &&
        Objects.equals(this.coordinates, locationDTO.coordinates) &&
        Objects.equals(this.evses, locationDTO.evses) &&
        Objects.equals(this.directions, locationDTO.directions) &&
        Objects.equals(this.operator, locationDTO.operator) &&
        Objects.equals(this.subOperator, locationDTO.subOperator) &&
        Objects.equals(this.owner, locationDTO.owner) &&
        Objects.equals(this.facilities, locationDTO.facilities) &&
        Objects.equals(this.images, locationDTO.images) &&
        Objects.equals(this.countryCode, locationDTO.countryCode) &&
        Objects.equals(this.partyId, locationDTO.partyId) &&
        Objects.equals(this.publishAllowedTo, locationDTO.publishAllowedTo) &&
        Objects.equals(this.postalCode, locationDTO.postalCode) &&
        Objects.equals(this.relatedLocations, locationDTO.relatedLocations) &&
        Objects.equals(this.parkingType, locationDTO.parkingType) &&
        Objects.equals(this.timeZone, locationDTO.timeZone) &&
        Objects.equals(this.openingTimes, locationDTO.openingTimes) &&
        Objects.equals(this.chargingWhenClosed, locationDTO.chargingWhenClosed) &&
        Objects.equals(this.energyMix, locationDTO.energyMix) &&
        Objects.equals(this.lastUpdated, locationDTO.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, publish, name, address, city, state, country, coordinates, evses, directions, operator, subOperator, owner, facilities, images, countryCode, partyId, publishAllowedTo, postalCode, relatedLocations, parkingType, timeZone, openingTimes, chargingWhenClosed, energyMix, lastUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    publish: ").append(toIndentedString(publish)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    evses: ").append(toIndentedString(evses)).append("\n");
    sb.append("    directions: ").append(toIndentedString(directions)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    subOperator: ").append(toIndentedString(subOperator)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    facilities: ").append(toIndentedString(facilities)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    publishAllowedTo: ").append(toIndentedString(publishAllowedTo)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    relatedLocations: ").append(toIndentedString(relatedLocations)).append("\n");
    sb.append("    parkingType: ").append(toIndentedString(parkingType)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    openingTimes: ").append(toIndentedString(openingTimes)).append("\n");
    sb.append("    chargingWhenClosed: ").append(toIndentedString(chargingWhenClosed)).append("\n");
    sb.append("    energyMix: ").append(toIndentedString(energyMix)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
