/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Price
 */



public class Price {
  @JsonProperty("exclVat")
  private Float exclVat = null;

  @JsonProperty("inclVat")
  private Float inclVat = null;

  public Price exclVat(Float exclVat) {
    this.exclVat = exclVat;
    return this;
  }

   /**
   * Get exclVat
   * @return exclVat
  **/
  @Schema(description = "")
  public Float getExclVat() {
    return exclVat;
  }

  public void setExclVat(Float exclVat) {
    this.exclVat = exclVat;
  }

  public Price inclVat(Float inclVat) {
    this.inclVat = inclVat;
    return this;
  }

   /**
   * Get inclVat
   * @return inclVat
  **/
  @Schema(description = "")
  public Float getInclVat() {
    return inclVat;
  }

  public void setInclVat(Float inclVat) {
    this.inclVat = inclVat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Price price = (Price) o;
    return Objects.equals(this.exclVat, price.exclVat) &&
        Objects.equals(this.inclVat, price.inclVat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exclVat, inclVat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Price {\n");
    
    sb.append("    exclVat: ").append(toIndentedString(exclVat)).append("\n");
    sb.append("    inclVat: ").append(toIndentedString(inclVat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
