/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PublishTokenType
 */



public class PublishTokenType {
  @JsonProperty("uid")
  private String uid = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    AD_HOC_USER("AD_HOC_USER"),
    APP_USER("APP_USER"),
    OTHER("OTHER"),
    RFID("RFID");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("visual_number")
  private String visualNumber = null;

  @JsonProperty("issuer")
  private String issuer = null;

  @JsonProperty("group_id")
  private String groupId = null;

  public PublishTokenType uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @Schema(description = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public PublishTokenType type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public PublishTokenType visualNumber(String visualNumber) {
    this.visualNumber = visualNumber;
    return this;
  }

   /**
   * Get visualNumber
   * @return visualNumber
  **/
  @Schema(description = "")
  public String getVisualNumber() {
    return visualNumber;
  }

  public void setVisualNumber(String visualNumber) {
    this.visualNumber = visualNumber;
  }

  public PublishTokenType issuer(String issuer) {
    this.issuer = issuer;
    return this;
  }

   /**
   * Get issuer
   * @return issuer
  **/
  @Schema(description = "")
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }

  public PublishTokenType groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @Schema(description = "")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublishTokenType publishTokenType = (PublishTokenType) o;
    return Objects.equals(this.uid, publishTokenType.uid) &&
        Objects.equals(this.type, publishTokenType.type) &&
        Objects.equals(this.visualNumber, publishTokenType.visualNumber) &&
        Objects.equals(this.issuer, publishTokenType.issuer) &&
        Objects.equals(this.groupId, publishTokenType.groupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, type, visualNumber, issuer, groupId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublishTokenType {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    visualNumber: ").append(toIndentedString(visualNumber)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
