/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * RegularHours
 */



public class RegularHours {
  @JsonProperty("weekday")
  private Integer weekday = null;

  @JsonProperty("period_begin")
  private String periodBegin = null;

  @JsonProperty("period_end")
  private String periodEnd = null;

  public RegularHours weekday(Integer weekday) {
    this.weekday = weekday;
    return this;
  }

   /**
   * Get weekday
   * @return weekday
  **/
  @Schema(description = "")
  public Integer getWeekday() {
    return weekday;
  }

  public void setWeekday(Integer weekday) {
    this.weekday = weekday;
  }

  public RegularHours periodBegin(String periodBegin) {
    this.periodBegin = periodBegin;
    return this;
  }

   /**
   * Get periodBegin
   * @return periodBegin
  **/
  @Schema(description = "")
  public String getPeriodBegin() {
    return periodBegin;
  }

  public void setPeriodBegin(String periodBegin) {
    this.periodBegin = periodBegin;
  }

  public RegularHours periodEnd(String periodEnd) {
    this.periodEnd = periodEnd;
    return this;
  }

   /**
   * Get periodEnd
   * @return periodEnd
  **/
  @Schema(description = "")
  public String getPeriodEnd() {
    return periodEnd;
  }

  public void setPeriodEnd(String periodEnd) {
    this.periodEnd = periodEnd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegularHours regularHours = (RegularHours) o;
    return Objects.equals(this.weekday, regularHours.weekday) &&
        Objects.equals(this.periodBegin, regularHours.periodBegin) &&
        Objects.equals(this.periodEnd, regularHours.periodEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weekday, periodBegin, periodEnd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegularHours {\n");
    
    sb.append("    weekday: ").append(toIndentedString(weekday)).append("\n");
    sb.append("    periodBegin: ").append(toIndentedString(periodBegin)).append("\n");
    sb.append("    periodEnd: ").append(toIndentedString(periodEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
