/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.extrawest.ocpi221emsp_client.client.model.CdrToken;
import com.extrawest.ocpi221emsp_client.client.model.ChargingPeriod;
import com.extrawest.ocpi221emsp_client.client.model.Price;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * SessionDTO
 */



public class SessionDTO {
  @JsonProperty("country_code")
  private String countryCode = null;

  @JsonProperty("party_id")
  private String partyId = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("start_date_time")
  private OffsetDateTime startDateTime = null;

  @JsonProperty("end_date_time")
  private OffsetDateTime endDateTime = null;

  @JsonProperty("kwh")
  private Float kwh = null;

  @JsonProperty("cdr_token")
  private CdrToken cdrToken = null;

  /**
   * Gets or Sets authMethod
   */
  public enum AuthMethodEnum {
    AUTH_REQUEST("AUTH_REQUEST"),
    COMMAND("COMMAND"),
    WHITELIST("WHITELIST");

    private String value;

    AuthMethodEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AuthMethodEnum fromValue(String input) {
      for (AuthMethodEnum b : AuthMethodEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("auth_method")
  private AuthMethodEnum authMethod = null;

  @JsonProperty("authorization_reference")
  private String authorizationReference = null;

  @JsonProperty("location_id")
  private String locationId = null;

  @JsonProperty("evse_uid")
  private String evseUid = null;

  @JsonProperty("connector_id")
  private String connectorId = null;

  @JsonProperty("meter_id")
  private String meterId = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("charging_periods")
  private List<ChargingPeriod> chargingPeriods = null;

  @JsonProperty("total_cost")
  private Price totalCost = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    COMPLETED("COMPLETED"),
    INVALID("INVALID"),
    PENDING("PENDING"),
    RESERVATION("RESERVATION");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("last_updated")
  private OffsetDateTime lastUpdated = null;

  public SessionDTO countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @Schema(required = true, description = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public SessionDTO partyId(String partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @Schema(required = true, description = "")
  public String getPartyId() {
    return partyId;
  }

  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }

  public SessionDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SessionDTO startDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Get startDateTime
   * @return startDateTime
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }

  public SessionDTO endDateTime(OffsetDateTime endDateTime) {
    this.endDateTime = endDateTime;
    return this;
  }

   /**
   * Get endDateTime
   * @return endDateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getEndDateTime() {
    return endDateTime;
  }

  public void setEndDateTime(OffsetDateTime endDateTime) {
    this.endDateTime = endDateTime;
  }

  public SessionDTO kwh(Float kwh) {
    this.kwh = kwh;
    return this;
  }

   /**
   * Get kwh
   * @return kwh
  **/
  @Schema(required = true, description = "")
  public Float getKwh() {
    return kwh;
  }

  public void setKwh(Float kwh) {
    this.kwh = kwh;
  }

  public SessionDTO cdrToken(CdrToken cdrToken) {
    this.cdrToken = cdrToken;
    return this;
  }

   /**
   * Get cdrToken
   * @return cdrToken
  **/
  @Schema(required = true, description = "")
  public CdrToken getCdrToken() {
    return cdrToken;
  }

  public void setCdrToken(CdrToken cdrToken) {
    this.cdrToken = cdrToken;
  }

  public SessionDTO authMethod(AuthMethodEnum authMethod) {
    this.authMethod = authMethod;
    return this;
  }

   /**
   * Get authMethod
   * @return authMethod
  **/
  @Schema(required = true, description = "")
  public AuthMethodEnum getAuthMethod() {
    return authMethod;
  }

  public void setAuthMethod(AuthMethodEnum authMethod) {
    this.authMethod = authMethod;
  }

  public SessionDTO authorizationReference(String authorizationReference) {
    this.authorizationReference = authorizationReference;
    return this;
  }

   /**
   * Get authorizationReference
   * @return authorizationReference
  **/
  @Schema(description = "")
  public String getAuthorizationReference() {
    return authorizationReference;
  }

  public void setAuthorizationReference(String authorizationReference) {
    this.authorizationReference = authorizationReference;
  }

  public SessionDTO locationId(String locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @Schema(required = true, description = "")
  public String getLocationId() {
    return locationId;
  }

  public void setLocationId(String locationId) {
    this.locationId = locationId;
  }

  public SessionDTO evseUid(String evseUid) {
    this.evseUid = evseUid;
    return this;
  }

   /**
   * Get evseUid
   * @return evseUid
  **/
  @Schema(required = true, description = "")
  public String getEvseUid() {
    return evseUid;
  }

  public void setEvseUid(String evseUid) {
    this.evseUid = evseUid;
  }

  public SessionDTO connectorId(String connectorId) {
    this.connectorId = connectorId;
    return this;
  }

   /**
   * Get connectorId
   * @return connectorId
  **/
  @Schema(required = true, description = "")
  public String getConnectorId() {
    return connectorId;
  }

  public void setConnectorId(String connectorId) {
    this.connectorId = connectorId;
  }

  public SessionDTO meterId(String meterId) {
    this.meterId = meterId;
    return this;
  }

   /**
   * Get meterId
   * @return meterId
  **/
  @Schema(description = "")
  public String getMeterId() {
    return meterId;
  }

  public void setMeterId(String meterId) {
    this.meterId = meterId;
  }

  public SessionDTO currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @Schema(required = true, description = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public SessionDTO chargingPeriods(List<ChargingPeriod> chargingPeriods) {
    this.chargingPeriods = chargingPeriods;
    return this;
  }

  public SessionDTO addChargingPeriodsItem(ChargingPeriod chargingPeriodsItem) {
    if (this.chargingPeriods == null) {
      this.chargingPeriods = new ArrayList<ChargingPeriod>();
    }
    this.chargingPeriods.add(chargingPeriodsItem);
    return this;
  }

   /**
   * Get chargingPeriods
   * @return chargingPeriods
  **/
  @Schema(description = "")
  public List<ChargingPeriod> getChargingPeriods() {
    return chargingPeriods;
  }

  public void setChargingPeriods(List<ChargingPeriod> chargingPeriods) {
    this.chargingPeriods = chargingPeriods;
  }

  public SessionDTO totalCost(Price totalCost) {
    this.totalCost = totalCost;
    return this;
  }

   /**
   * Get totalCost
   * @return totalCost
  **/
  @Schema(description = "")
  public Price getTotalCost() {
    return totalCost;
  }

  public void setTotalCost(Price totalCost) {
    this.totalCost = totalCost;
  }

  public SessionDTO status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SessionDTO lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionDTO sessionDTO = (SessionDTO) o;
    return Objects.equals(this.countryCode, sessionDTO.countryCode) &&
        Objects.equals(this.partyId, sessionDTO.partyId) &&
        Objects.equals(this.id, sessionDTO.id) &&
        Objects.equals(this.startDateTime, sessionDTO.startDateTime) &&
        Objects.equals(this.endDateTime, sessionDTO.endDateTime) &&
        Objects.equals(this.kwh, sessionDTO.kwh) &&
        Objects.equals(this.cdrToken, sessionDTO.cdrToken) &&
        Objects.equals(this.authMethod, sessionDTO.authMethod) &&
        Objects.equals(this.authorizationReference, sessionDTO.authorizationReference) &&
        Objects.equals(this.locationId, sessionDTO.locationId) &&
        Objects.equals(this.evseUid, sessionDTO.evseUid) &&
        Objects.equals(this.connectorId, sessionDTO.connectorId) &&
        Objects.equals(this.meterId, sessionDTO.meterId) &&
        Objects.equals(this.currency, sessionDTO.currency) &&
        Objects.equals(this.chargingPeriods, sessionDTO.chargingPeriods) &&
        Objects.equals(this.totalCost, sessionDTO.totalCost) &&
        Objects.equals(this.status, sessionDTO.status) &&
        Objects.equals(this.lastUpdated, sessionDTO.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, partyId, id, startDateTime, endDateTime, kwh, cdrToken, authMethod, authorizationReference, locationId, evseUid, connectorId, meterId, currency, chargingPeriods, totalCost, status, lastUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionDTO {\n");
    
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
    sb.append("    kwh: ").append(toIndentedString(kwh)).append("\n");
    sb.append("    cdrToken: ").append(toIndentedString(cdrToken)).append("\n");
    sb.append("    authMethod: ").append(toIndentedString(authMethod)).append("\n");
    sb.append("    authorizationReference: ").append(toIndentedString(authorizationReference)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    evseUid: ").append(toIndentedString(evseUid)).append("\n");
    sb.append("    connectorId: ").append(toIndentedString(connectorId)).append("\n");
    sb.append("    meterId: ").append(toIndentedString(meterId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    chargingPeriods: ").append(toIndentedString(chargingPeriods)).append("\n");
    sb.append("    totalCost: ").append(toIndentedString(totalCost)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
