/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * OpenAPI spec version: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.extrawest.ocpi221emsp_client.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SignedValue
 */



public class SignedValue {
  @JsonProperty("plainDat")
  private String plainDat = null;

  @JsonProperty("nature")
  private String nature = null;

  @JsonProperty("plain_data")
  private String plainData = null;

  @JsonProperty("signed_data")
  private String signedData = null;

  public SignedValue plainDat(String plainDat) {
    this.plainDat = plainDat;
    return this;
  }

   /**
   * Get plainDat
   * @return plainDat
  **/
  @Schema(description = "")
  public String getPlainDat() {
    return plainDat;
  }

  public void setPlainDat(String plainDat) {
    this.plainDat = plainDat;
  }

  public SignedValue nature(String nature) {
    this.nature = nature;
    return this;
  }

   /**
   * Get nature
   * @return nature
  **/
  @Schema(description = "")
  public String getNature() {
    return nature;
  }

  public void setNature(String nature) {
    this.nature = nature;
  }

  public SignedValue plainData(String plainData) {
    this.plainData = plainData;
    return this;
  }

   /**
   * Get plainData
   * @return plainData
  **/
  @Schema(description = "")
  public String getPlainData() {
    return plainData;
  }

  public void setPlainData(String plainData) {
    this.plainData = plainData;
  }

  public SignedValue signedData(String signedData) {
    this.signedData = signedData;
    return this;
  }

   /**
   * Get signedData
   * @return signedData
  **/
  @Schema(description = "")
  public String getSignedData() {
    return signedData;
  }

  public void setSignedData(String signedData) {
    this.signedData = signedData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignedValue signedValue = (SignedValue) o;
    return Objects.equals(this.plainDat, signedValue.plainDat) &&
        Objects.equals(this.nature, signedValue.nature) &&
        Objects.equals(this.plainData, signedValue.plainData) &&
        Objects.equals(this.signedData, signedValue.signedData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plainDat, nature, plainData, signedData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignedValue {\n");
    
    sb.append("    plainDat: ").append(toIndentedString(plainDat)).append("\n");
    sb.append("    nature: ").append(toIndentedString(nature)).append("\n");
    sb.append("    plainData: ").append(toIndentedString(plainData)).append("\n");
    sb.append("    signedData: ").append(toIndentedString(signedData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
